--Console.Execute("clear")
Console.Execute("toggleconsole")
Console.Log("default text with no arguments")
Console.Log("black text", Console.Color.Black)
Console.Log("dark blue text", Console.Color.DarkBlue)
Console.Log("dark green text", Console.Color.DarkGreen)
Console.Log("dark cyan text", Console.Color.DarkCyan)
Console.Log("dark red text", Console.Color.DarkRed)
Console.Log("dark magenta text", Console.Color.DarkMagenta)
Console.Log("dark yellow text", Console.Color.DarkYellow)
Console.Log("gray text", Console.Color.Gray)
Console.Log("dark gray text", Console.Color.DarkGray)
Console.Log("blue text", Console.Color.Blue)
Console.Log("green text", Console.Color.Green)
Console.Log("cyan text", Console.Color.Cyan)
Console.Log("red text", Console.Color.Red)
Console.Log("magenta text", Console.Color.Magenta)
Console.Log("yellow text", Console.Color.Yellow)
Console.Log("white text", Console.Color.White)
Console.Log("default text", Console.Color.Default)

function Frame()
	Gfx.Clear(0.25, 0.25, 0.25, 1.0)
end